import { useNavigate } from "react-router-dom";

export default function Checkout({ cart }) {
  const navigate = useNavigate();

  const total = cart.reduce((sum, item) => sum + item.price * item.qty, 0);

  const handlePayment = async () => {
    try {
      const amount = total > 0 ? total : 500;

      // Backend URL
      const createOrderUrl =
        import.meta.env.VITE_API_URL || "http://127.0.0.1:5000/create-order";

      console.log("=================================");
      console.log("STARTING PAYMENT");
      console.log("Amount:", amount);
      console.log("Create Order URL:", createOrderUrl);
      console.log("=================================");

      // =====================================================
      // STEP 1: CREATE RAZORPAY ORDER
      // =====================================================

      const orderResponse = await fetch(createOrderUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          amount,
        }),
      });

      if (!orderResponse.ok) {
        const errorText = await orderResponse.text();

        throw new Error(errorText || "Failed to create Razorpay order");
      }

      const data = await orderResponse.json();

      console.log("Create Order Response:", data);

      if (!data.success || !data.order?.id) {
        console.error("Invalid order response:", data);
        throw new Error("Razorpay Order ID missing from backend");
      }

      const order = data.order;

      console.log("Razorpay Order:", order);
      console.log("Razorpay Order ID:", order.id);
      // VERY IMPORTANT
      if (!order.id) {
        throw new Error("Razorpay Order ID missing from backend");
      }

      // =====================================================
      // STEP 2: CHECK RAZORPAY SDK
      // =====================================================

      if (!window.Razorpay) {
        alert("Razorpay SDK is not loaded. Please refresh the page.");
        return;
      }

      // =====================================================
      // STEP 3: RAZORPAY CHECKOUT
      // =====================================================

      const options = {
        key: "rzp_test_SmL7NiqXstHBPR",

        amount: order.amount,

        currency: order.currency || "INR",

        name: "Scalable Payment Processing System",

        description: "Test Transaction",

        // IMPORTANT
        // Always use the order ID generated by backend
        order_id: order.id,

        handler: async function (paymentResponse) {
          console.log("========== RAZORPAY PAYMENT RESPONSE ==========");

          console.log("Full Payment Response:", paymentResponse);

          console.log("Payment ID:", paymentResponse?.razorpay_payment_id);

          console.log("Returned Order ID:", paymentResponse?.razorpay_order_id);

          console.log("Signature:", paymentResponse?.razorpay_signature);

          console.log("Server Order ID:", order.id);

          console.log("===============================================");

          try {
            // =================================================
            // STEP 4: EXTRACT PAYMENT DETAILS
            // =================================================

            const paymentId = paymentResponse?.razorpay_payment_id;

            // Use backend-created order ID.
            // This is more reliable and follows Razorpay's
            // server-side verification recommendation.
            const orderId = order.id;

            const signature = paymentResponse?.razorpay_signature;

            // =================================================
            // STEP 5: VALIDATE RESPONSE BEFORE API CALL
            // =================================================

            if (!paymentId) {
              console.error("Payment ID missing:", paymentResponse);

              alert("Payment completed, but Payment ID was not received.");

              return;
            }

            if (!signature) {
              console.error("Razorpay Signature missing:", paymentResponse);

              alert(
                "Payment completed, but Razorpay signature was not received.",
              );

              return;
            }

            if (!orderId) {
              console.error("Order ID missing:", order);

              alert("Payment completed, but Order ID was missing.");

              return;
            }

            // =================================================
            // STEP 6: SEND PAYMENT TO BACKEND
            // =================================================

            const verifyUrl = "http://127.0.0.1:5000/api/payments/verify";

            console.log("========== SENDING VERIFICATION ==========");

            console.log({
              razorpay_order_id: orderId,
              razorpay_payment_id: paymentId,
              razorpay_signature: signature,
              amount: amount,
              currency: order.currency || "INR",
            });

            console.log("===========================================");

            const verifyResponse = await fetch(verifyUrl, {
              method: "POST",

              headers: {
                "Content-Type": "application/json",
              },

              body: JSON.stringify({
                razorpay_order_id: orderId,

                razorpay_payment_id: paymentId,

                razorpay_signature: signature,

                amount: amount,

                currency: order.currency || "INR",
              }),
            });

            // =================================================
            // STEP 7: READ BACKEND RESPONSE
            // =================================================

            const verificationResult = await verifyResponse.json();

            console.log("========== VERIFICATION RESULT ==========");

            console.log(verificationResult);

            console.log("==========================================");

            // =================================================
            // STEP 8: SUCCESS
            // =================================================

            if (verifyResponse.ok && verificationResult.success) {
              console.log("Transaction saved:", verificationResult.transaction);
              navigate("/payment-success");
            } else {
              // =================================================
              // STEP 9: VERIFICATION FAILED
              // =================================================

              console.error("Payment verification failed:", verificationResult);

              navigate("/payment-failed");
            }
          } catch (error) {
            console.error("Verification error:", error);

            navigate("/payment-failed");
          }
        },

        // =====================================================
        // USER CLOSES RAZORPAY
        // =====================================================

        modal: {
          ondismiss: function () {
            console.log("Razorpay checkout closed by user.");
          },
        },

        // =====================================================
        // RAZORPAY THEME
        // =====================================================

        theme: {
          color: "#3399cc",
        },
      };

      // =====================================================
      // STEP 9: CREATE RAZORPAY INSTANCE
      // =====================================================

      const razorpay = new window.Razorpay(options);

      // =====================================================
      // STEP 10: PAYMENT FAILURE
      // =====================================================

      razorpay.on("payment.failed", function (response) {
        console.error("========== PAYMENT FAILED ==========");

        console.error(response.error);

        console.error("====================================");

        navigate("/payment-failed");
      });

      // =====================================================
      // STEP 11: OPEN CHECKOUT
      // =====================================================

      razorpay.open();
    } catch (error) {
      console.error("Payment initialization error:", error);

      alert("Unable to start payment. Check the browser console.");
    }
  };

  return (
    <div className="min-h-screen bg-gray-100 p-6">
      <h1 className="text-2xl font-bold mb-4">Checkout</h1>

      <div className="bg-white p-6 rounded shadow">
        {cart.length === 0 ? (
          <div>
            <p>Your cart is empty.</p>

            <button
              onClick={handlePayment}
              className="mt-6 w-full bg-gray-300 text-white px-4 py-2 rounded"
            >
              Pay Now
            </button>

            <button
              onClick={() => navigate("/")}
              className="mt-2 w-full bg-gray-300 py-2 rounded"
            >
              Back to Home
            </button>
          </div>
        ) : (
          <div>
            <ul className="mb-4">
              {cart.map((item) => (
                <li key={item.id} className="flex justify-between mb-2">
                  <span>
                    {item.name} x {item.qty}
                  </span>

                  <span>₹{item.price * item.qty}</span>
                </li>
              ))}
            </ul>

            <div className="flex justify-between font-bold text-lg">
              <span>Total:</span>

              <span>₹{total}</span>
            </div>

            <button
              onClick={handlePayment}
              className="mt-6 w-full bg-green-600 text-white px-4 py-2 rounded"
            >
              Pay Now
            </button>

            <button
              onClick={() => navigate("/")}
              className="mt-2 w-full bg-gray-300 py-2 rounded"
            >
              Back to Home
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
